import { describe, expect, test } from "bun:test";
import { parseRegistry, serializeRegistry } from "./depsRegistry.ts";

const rows = [
  { package: "zod", version: "3.23.8", repo: "github.com/colinhacks/zod", clonedAtSha: "a".repeat(40) },
  { package: "convex", version: "1.17.4", repo: "github.com/get-convex/convex-backend", clonedAtSha: `${"b".repeat(40)} (no tag match)` },
];
const GOLDEN = `# Dependency Source Clones

> GENERATED by \`harness deps\` — clone directories are gitignored; this registry is committed.
> Skills read this table before specs/implementation to consult real source at the pinned version.

| package | version | repo | cloned_at_sha |
| --- | --- | --- | --- |
| convex | 1.17.4 | github.com/get-convex/convex-backend | ${"b".repeat(40)} (no tag match) |
| zod | 3.23.8 | github.com/colinhacks/zod | ${"a".repeat(40)} |
`;

describe("depsRegistry", () => {
  test("serialize sorts by package and matches golden", () => {
    expect(serializeRegistry({ rows })).toBe(GOLDEN);
  });
  test("parse(serialize(x)) round-trips; header-only → []", () => {
    expect(parseRegistry({ text: GOLDEN })).toEqual([rows[1]!, rows[0]!]);
    expect(parseRegistry({ text: serializeRegistry({ rows: [] }) })).toEqual([]);
  });
  test("malformed rows are skipped, not thrown", () => {
    expect(parseRegistry({ text: "| broken |\nprose\n| a | b | c | d |\n" })).toEqual([
      { package: "a", version: "b", repo: "c", clonedAtSha: "d" },
    ]);
  });
});
