import { readFileSync } from "node:fs";
import { join } from "node:path";
import { writeFileAtomic } from "./fsx.ts";
import { P } from "./paths.ts";

/** One row of .agent/dependencies/registry.md. */
export interface RegistryRow {
  package: string; // name as pinned in the project manifest
  version: string; // version the clone targeted
  repo: string; // DependencyPin.repo verbatim
  clonedAtSha: string; // clone HEAD sha; "<sha> (no tag match)" when default branch was used
}

const HEADER = `# Dependency Source Clones

> GENERATED by \`harness deps\` — clone directories are gitignored; this registry is committed.
> Skills read this table before specs/implementation to consult real source at the pinned version.

| package | version | repo | cloned_at_sha |
| --- | --- | --- | --- |
`;

/**
 * Serializes rows to registry.md (sorted by package — deterministic).
 *
 * @param props.rows - Rows in any order.
 * @returns Full file content, trailing newline included.
 */
export function serializeRegistry(props: { rows: RegistryRow[] }): string {
  const rows = [...props.rows].sort((a, b) => a.package.localeCompare(b.package));
  return HEADER + rows.map((r) => `| ${r.package} | ${r.version} | ${r.repo} | ${r.clonedAtSha} |\n`).join("");
}

/**
 * Parses registry.md tolerantly: only 4-cell `| a | b | c | d |` body rows count; header,
 * separator, prose, and malformed rows are skipped (never throws — hand-edits must not brick
 * doctor).
 *
 * @param props.text - File content.
 * @returns Rows in file order.
 */
export function parseRegistry(props: { text: string }): RegistryRow[] {
  const rows: RegistryRow[] = [];
  for (const line of props.text.split("\n")) {
    if (!line.startsWith("|")) continue;
    const cells = line.replace(/^\|/, "").replace(/\|\s*$/, "").split("|").map((c) => c.trim());
    if (cells.length !== 4 || cells[0] === "package" || cells[0] === "---") continue;
    rows.push({ package: cells[0]!, version: cells[1]!, repo: cells[2]!, clonedAtSha: cells[3]! });
  }
  return rows;
}

/**
 * Loads the registry.
 *
 * @param props.root - Project root.
 * @returns Rows; [] when the file is absent.
 */
export function loadRegistry(props: { root: string }): RegistryRow[] {
  try {
    return parseRegistry({ text: readFileSync(join(props.root, P.depsRegistry), "utf8") });
  } catch {
    return [];
  }
}

/**
 * Writes the registry atomically.
 *
 * @param props.root - Project root.
 * @param props.rows - Rows to persist.
 * @returns Nothing.
 */
export function saveRegistry(props: { root: string; rows: RegistryRow[] }): void {
  writeFileAtomic({ path: join(props.root, P.depsRegistry), content: serializeRegistry({ rows: props.rows }) });
}
