import type { BridgePlan, PlatformAdapter, ProjectContext } from "./types.ts";

/** The managed settings fragment sync merges into .claude/settings.json (D10 merge path). */
export const CLAUDE_SETTINGS_FRAGMENT: Record<string, unknown> = {
  hooks: {
    SessionStart: [{ hooks: [{ type: "command", command: "harness doctor" }] }],
  },
};

/** Proposal §17 routing directive, verbatim, plus the Claude-specific context note. */
const CLAUDE_MD = `@.agent/AGENTS.md

<!-- GENERATED by harness sync — do not edit. Edit .agent/AGENTS.md instead. -->

At the start of every message, classify the intent:
  - "I need to debug / something is broken / this isn't working" → load debug/SKILL.md
  - "write a spec / spec out X / what should we build" → load dev-spec/SKILL.md
  - "implement / build this / run the spec" → load implement/SKILL.md
  - "commit / generate commit message / end of session" → load commit/SKILL.md
  - "sync spec / update the spec / extract patterns" → load sync-spec/SKILL.md
  - "polish / review the code / check for completeness" → load polish/SKILL.md
  - "research / learn about / how does X work" → load research/SKILL.md or learn/SKILL.md
  - General project question → read state.md, answer from harness context

If ambiguous, proceed with current skill but note the classification at top of response.

Claude Code has no native context injection: before writing or editing code for a
spec, run \`harness context --for <path>\` and read every file it lists.
`;

/**
 * Claude Code bridge planner (master §9.2 rows 8–10). Pure — string building only.
 * Symlinks the shared skills dir; generates the thin CLAUDE.md and the settings fragment
 * (applied via mergeManagedJson, never whole-file clobbered).
 */
export const claudeAdapter: PlatformAdapter = {
  id: "claude",
  dir: ".claude",
  plan(props: { ctx: ProjectContext }): BridgePlan {
    return {
      symlinks: [{ linkPath: ".claude/skills", targetPath: ".agent/skills" }],
      files: [
        { path: ".claude/CLAUDE.md", content: CLAUDE_MD },
        { path: ".claude/settings.json", content: `${JSON.stringify(CLAUDE_SETTINGS_FRAGMENT, null, 2)}\n` },
      ],
      gitignoreLines: props.ctx.manifest.platforms.commit_bridges === true ? [] : [".claude/"],
    };
  },
};
