import type { BridgePlan, PlatformAdapter, ProjectContext } from "./types.ts";

/** The managed settings fragment sync merges into .claude/settings.json (D10 merge path). */
export const CLAUDE_SETTINGS_FRAGMENT: Record<string, unknown> = {
  hooks: {
    SessionStart: [{ hooks: [{ type: "command", command: "harness doctor" }] }],
  },
};

/** Proposal §17 routing directive, verbatim, plus the Claude-specific context note. */
const CLAUDE_MD = `@.agent/AGENTS.md

<!-- GENERATED by harness sync — do not edit. Edit .agent/AGENTS.md instead. -->

At the start of every message, classify the intent:
  - "I need to debug / something is broken / this isn't working" → load debug/SKILL.md
  - "write a spec / spec out X / what should we build" → load dev-spec/SKILL.md
  - "implement / build this / run the spec" → load implement/SKILL.md
  - "commit / generate commit message / end of session" → load commit/SKILL.md
  - "sync spec / update the spec / extract patterns" → load sync-spec/SKILL.md
  - "polish / review the code / check for completeness" → load polish/SKILL.md
  - "research / learn about / how does X work" → load research/SKILL.md or learn/SKILL.md
  - General project question → read state.md, answer from harness context

If ambiguous, proceed with current skill but note the classification at top of response.

Claude Code has no native context injection: before writing or editing code for a
spec, run \`harness context --for <path>\` and read every file it lists.
`;

/** Slash-command shim: `.claude/commands/<name>.md` → `/name`. `init` ships as
 * `harness-init.md` — Claude Code's builtin `/init` collides (09 D09-2). */
function commandShim(props: { name: string; description: string }): string {
  return `---
description: ${props.description}
---

<!-- GENERATED by harness sync — do not edit. Edit .agent/skills/${props.name}/SKILL.md instead. -->
Invoke the \`${props.name}\` skill: read \`.agent/skills/${props.name}/SKILL.md\` and follow it exactly,
starting with its Preflight. Arguments: $ARGUMENTS
`;
}

/**
 * Claude Code bridge planner (master §9.2 rows 8–10). Pure — string building only.
 * Symlinks the shared skills dir; generates the thin CLAUDE.md, one command shim per
 * described skill, and the settings fragment (applied via mergeManagedJson).
 */
export const claudeAdapter: PlatformAdapter = {
  id: "claude",
  dir: ".claude",
  plan(props: { ctx: ProjectContext }): BridgePlan {
    const files: BridgePlan["files"] = [
      { path: ".claude/CLAUDE.md", content: CLAUDE_MD },
      { path: ".claude/settings.json", content: `${JSON.stringify(CLAUDE_SETTINGS_FRAGMENT, null, 2)}\n` },
    ];
    for (const skill of [...props.ctx.skills].sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const description = skill.frontmatter["description"];
      if (typeof description !== "string" || description === "") continue;
      const fileName = skill.name === "init" ? "harness-init" : skill.name;
      files.push({ path: `.claude/commands/${fileName}.md`, content: commandShim({ name: skill.name, description }) });
    }
    files.sort((a, b) => (a.path < b.path ? -1 : 1));
    return {
      symlinks: [{ linkPath: ".claude/skills", targetPath: ".agent/skills" }],
      files,
      gitignoreLines: props.ctx.manifest.platforms.commit_bridges === true ? [] : [".claude/"],
    };
  },
};
