import { describe, expect, test } from "bun:test";
import { loadProjectContext } from "../commands/sync.ts";
import { mkTmpProject, rmProject } from "../../test/helpers.ts";
import { claudeAdapter } from "./claude.ts";

const CLAUDE_MD_GOLDEN = `@.agent/AGENTS.md

<!-- GENERATED by harness sync — do not edit. Edit .agent/AGENTS.md instead. -->

At the start of every message, classify the intent:
  - "I need to debug / something is broken / this isn't working" → load debug/SKILL.md
  - "write a spec / spec out X / what should we build" → load dev-spec/SKILL.md
  - "implement / build this / run the spec" → load implement/SKILL.md
  - "commit / generate commit message / end of session" → load commit/SKILL.md
  - "sync spec / update the spec / extract patterns" → load sync-spec/SKILL.md
  - "polish / review the code / check for completeness" → load polish/SKILL.md
  - "research / learn about / how does X work" → load research/SKILL.md or learn/SKILL.md
  - General project question → read state.md, answer from harness context

If ambiguous, proceed with current skill but note the classification at top of response.

Claude Code has no native context injection: before writing or editing code for a
spec, run \`harness context --for <path>\` and read every file it lists.
`;

const SETTINGS_GOLDEN = `{
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "harness doctor"
          }
        ]
      }
    ]
  }
}
`;

describe("claudeAdapter.plan", () => {
  test("symlink, goldens, command shims, gitignore", () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const { ctx } = loadProjectContext({ root: dir });
    const plan = claudeAdapter.plan({ ctx });
    const file = (p: string) => plan.files.find((f) => f.path === p)?.content;
    expect(plan.symlinks).toEqual([{ linkPath: ".claude/skills", targetPath: ".agent/skills" }]);
    expect(plan.files.map((f) => f.path)).toEqual([
      ".claude/CLAUDE.md",
      ".claude/commands/dev-spec.md",
      ".claude/commands/implement.md",
      ".claude/settings.json",
    ]);
    expect(file(".claude/CLAUDE.md")).toBe(CLAUDE_MD_GOLDEN);
    expect(file(".claude/settings.json")).toBe(SETTINGS_GOLDEN);
    expect(file(".claude/commands/dev-spec.md")).toContain("Invoke the `dev-spec` skill");
    expect(file(".claude/commands/dev-spec.md")).toContain("$ARGUMENTS");
    expect(plan.gitignoreLines).toEqual([".claude/"]);
    rmProject({ dir });
  });

  test("init skill ships as /harness-init (builtin /init collision)", () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const { ctx } = loadProjectContext({ root: dir });
    const ctx2 = {
      ...ctx,
      skills: [...ctx.skills, { name: "init", dir: ".agent/skills/init", frontmatter: { name: "init", description: "Init the harness." } }],
    };
    const paths = claudeAdapter.plan({ ctx: ctx2 }).files.map((f) => f.path);
    expect(paths).toContain(".claude/commands/harness-init.md");
    expect(paths).not.toContain(".claude/commands/init.md");
    rmProject({ dir });
  });
});
