import { describe, expect, test } from "bun:test";
import { loadProjectContext } from "../commands/sync.ts";
import { mkTmpProject, rmProject } from "../../test/helpers.ts";
import { ompAdapter } from "./omp.ts";

const AGENT_IMPLEMENT_GOLDEN = `---
name: implement
description: Drive spec implementation task-group by task-group. Triggers on "implement", "build this", "run the spec".
model: "@task"
---

<!-- GENERATED by harness sync — do not edit -->
## Preflight
1. If \`.agent/manifest.json\` is missing → stop; tell the user to run \`harness init\`.
2. Run \`harness doctor\`. Fix 🔴 errors before proceeding.
3. Run \`harness state\` and read the output.

## Task
Load the skill \`implement\` and follow it exactly.
`;

const INSTR_BACKEND_0_GOLDEN = `---
applyTo: "convex/**"
---

<!-- GENERATED by harness sync — do not edit -->
Before creating or editing files matched by this rule, read:

- .agent/docs/standards/backend/api.md
`;

// V1–V4, V9 verified: exact-id matching; ids are "agents" (single) + "claude".
const CONFIG_GOLDEN = `# GENERATED by harness sync — do not edit (harness manages this whole file).
# Disables OMP's native ingestion of directories the harness already bridges,
# so .agent/ content never loads twice (harness spec 00 §3 C4).
disabledProviders:
  - agents
  - claude

# Model role overrides — uncomment and edit to customize (roles: default, smol,
# slow, vision, plan, designer, commit, tiny, task, advisor).
# modelRoles:
#   task: "<provider/model>"
`;

// V7/V8 verified: handler is (event, ctx); HookAPI imports from the package root.
const HOOK_GOLDEN = `// GENERATED by harness sync — do not edit.
import type { HookAPI } from "@oh-my-pi/pi-coding-agent";

/** On session start, run \`harness doctor --json\` and surface errors without blocking. */
export default function (pi: HookAPI) {
  pi.on("session_start", async (_event, ctx) => {
    try {
      const proc = Bun.spawn(["harness", "doctor", "--json"], { stdout: "pipe", stderr: "pipe" });
      const out = await new Response(proc.stdout).text();
      await proc.exited;
      const errors = (JSON.parse(out) as Array<{ level: string }>).filter((i) => i.level === "error");
      if (errors.length > 0) ctx.ui.notify(\`harness doctor: \${errors.length} error(s) — run harness doctor\`, "warning");
    } catch {} // harness missing or doctor crashed — never block a session.
  });
}
`;

describe("ompAdapter.plan", () => {
  const dir = mkTmpProject({ fixture: "initialized" });
  const { ctx } = loadProjectContext({ root: dir });
  const plan = ompAdapter.plan({ ctx });
  const file = (p: string) => plan.files.find((f) => f.path === p)?.content;

  test("symlinks + gitignore + full sorted file set", () => {
    expect(plan.symlinks).toEqual([
      { linkPath: ".omp/AGENTS.md", targetPath: ".agent/AGENTS.md" },
      { linkPath: ".omp/skills", targetPath: ".agent/skills" },
    ]);
    expect(plan.gitignoreLines).toEqual([".omp/"]);
    expect(plan.files.map((f) => f.path)).toEqual([
      ".omp/agents/dev-spec.md",
      ".omp/agents/implement.md",
      ".omp/config.yml",
      ".omp/hooks/session-doctor.ts",
      ".omp/instructions/naming-0.instructions.md",
      ".omp/instructions/naming-1.instructions.md",
      ".omp/instructions/naming-2.instructions.md",
      ".omp/instructions/std-backend-0.instructions.md",
      ".omp/instructions/std-backend-1.instructions.md",
    ]);
  });

  test("goldens: agent / instructions / config / hook", () => {
    expect(file(".omp/agents/implement.md")).toBe(AGENT_IMPLEMENT_GOLDEN);
    expect(file(".omp/agents/dev-spec.md")).not.toContain("model:"); // no role → no model line
    expect(file(".omp/instructions/std-backend-0.instructions.md")).toBe(INSTR_BACKEND_0_GOLDEN);
    expect(file(".omp/instructions/std-backend-1.instructions.md")).toContain('applyTo: "src/server/**"');
    expect(file(".omp/instructions/naming-0.instructions.md")).toContain("- .agent/docs/standards/naming-conventions.md");
    expect(file(".omp/config.yml")).toBe(CONFIG_GOLDEN);
    expect(file(".omp/hooks/session-doctor.ts")).toBe(HOOK_GOLDEN);
  });

  test("anti-pattern rules file only when a pattern: line exists", () => {
    expect(file(".omp/rules/anti-patterns.md")).toBeUndefined();
    const ctx2 = { ...ctx, antiPatternRegexes: ["\\bany\\b"] };
    const rules = ompAdapter.plan({ ctx: ctx2 }).files.find((f) => f.path === ".omp/rules/anti-patterns.md");
    expect(rules?.content).toContain(`condition: ["\\\\bany\\\\b"]`);
    expect(rules?.content).toContain("interruptMode: prose-only");
  });

  test("commit_bridges suppresses gitignore line", () => {
    const ctx2 = { ...ctx, manifest: { ...ctx.manifest, platforms: { ...ctx.manifest.platforms, commit_bridges: true } } };
    expect(ompAdapter.plan({ ctx: ctx2 }).gitignoreLines).toEqual([]);
    rmProject({ dir });
  });
});
