import type { BridgePlan, PlatformAdapter, ProjectContext } from "./types.ts";

/** Skills that always get an OMP subagent when present on disk (plus any with harness_model_role). */
export const ROUTED_SKILLS = ["dev-spec", "sync-spec", "implement", "polish", "debug", "commit"] as const;

/** Provider ids OMP must not double-ingest in harness projects (04 Verified Constants V2–V4). */
export const OMP_DISABLED_PROVIDERS = ["agents", "claude"] as const;

const GENERATED_MARKER = "<!-- GENERATED by harness sync — do not edit -->";

const PREFLIGHT = `## Preflight
1. If \`.agent/manifest.json\` is missing → stop; tell the user to run \`harness init\`.
2. Run \`harness doctor\`. Fix 🔴 errors before proceeding.
3. Run \`harness state\` and read the output.`;

/** OMP subagent file for one routed skill (C1: name + description are required). */
function agentFile(props: { name: string; description: string; role: string | null }): string {
  const modelLine = props.role !== null ? `model: "@${props.role}"\n` : "";
  return `---
name: ${props.name}
description: ${props.description}
${modelLine}---

${GENERATED_MARKER}
${PREFLIGHT}

## Task
Load the skill \`${props.name}\` and follow it exactly.
`;
}

/** One instructions file per glob (V5: applyTo is a single glob string). */
function instructionsFile(props: { glob: string; inject: string[] }): string {
  return `---
applyTo: "${props.glob}"
---

${GENERATED_MARKER}
Before creating or editing files matched by this rule, read:

${props.inject.map((p) => `- .agent/${p}`).join("\n")}
`;
}

/** Builds .omp/config.yml (advisor + model roles manifest-driven). */
export function ompConfigFile(props: {
  advisor: boolean;
  tiers: { frontier: string; standard: string; cheap: string };
}): string {
  // Map harness tiers onto OMP roles so subagents/advisor REALLY run cheaper models —
  // unmapped roles fall back to the session model (OMP #985), which is exactly the
  // "everything silently runs the frontier model" failure this prevents. "@role" tier
  // values skip the line (the developer manages that role in OMP directly).
  const roleLines = (
    [
      ["slow", props.tiers.frontier],
      ["task", props.tiers.standard],
      ["smol", props.tiers.cheap],
      ["tiny", props.tiers.cheap],
      ["advisor", props.tiers.cheap],
    ] as const
  )
    .filter(([, model]) => !model.startsWith("@"))
    .map(([role, model]) => `  ${role}: "${model}"`);

  return `# GENERATED by harness sync — do not edit (harness manages this whole file).
# Disables OMP's native ingestion of directories the harness already bridges,
# so .agent/ content never loads twice (harness spec 00 §3 C4).
disabledProviders:
${OMP_DISABLED_PROVIDERS.map((id) => `  - ${id}`).join("\n")}

# Harness advisor (WATCHDOG.yml defines it; models.advisor in manifest.json toggles it).
advisor:
  enabled: ${props.advisor}

# Model roles from manifest.json#models.tiers — edit the manifest, then \`harness sync\`.
${roleLines.length > 0 ? `modelRoles:\n${roleLines.join("\n")}` : "# modelRoles: (tiers are @role refs — roles managed in OMP directly)"}
`;
}

/** Exported for the install bootstrap (double-load guard must exist pre-init;
 * advisor + default tiers apply — the manifest-driven sync corrects them after init). */
export const OMP_CONFIG_FILE = ompConfigFile({
  advisor: true,
  tiers: { frontier: "anthropic/claude-fable-5", standard: "anthropic/claude-sonnet-5", cheap: "anthropic/claude-haiku-4-5" },
});

/** The harness-keeper advisor roster (OMP-native: src/advisor reads .omp/WATCHDOG.yml).
 * The model is EXPLICIT (tiers.cheap) — role-based resolution proved unreliable in live
 * testing ("no model assigned to the 'advisor' role" despite modelRoles mapping). An
 * "@role" tier ref omits the line and falls back to OMP's advisor-role resolution. */
export function watchdogFile(props: { cheapModel: string }): string {
  const modelLine = props.cheapModel.startsWith("@") ? "" : `    model: "${props.cheapModel}"\n`;
  return `# GENERATED by harness sync — do not edit. Edit .agent/skills/harness-advisor/ instead.
advisors:
  - name: harness-keeper
${modelLine}    tools: ["read", "grep", "glob", "bash"]
    instructions: |
      Read .agent/skills/harness-advisor/references/advisor-protocol.md and follow it exactly.
      You are the harness keeper: watch the developer's words for requirement shifts
      (especially absolutes like "always"/"never"/"from now on"), map them to the harness
      files that must change, interject one complete change-set, append it to
      .agent/docs/harness-changelog.md, and relay what changed back to the developer.
`;
}

const HOOK_FILE = `// GENERATED by harness sync — do not edit.
import type { HookAPI } from "@oh-my-pi/pi-coding-agent";

/** On session start, run \`harness doctor --json\` and surface errors without blocking. */
export default function (pi: HookAPI) {
  pi.on("session_start", async (_event, ctx) => {
    try {
      const proc = Bun.spawn(["harness", "doctor", "--json"], { stdout: "pipe", stderr: "pipe" });
      const out = await new Response(proc.stdout).text();
      await proc.exited;
      const errors = (JSON.parse(out) as Array<{ level: string }>).filter((i) => i.level === "error");
      if (errors.length > 0) ctx.ui.notify(\`harness doctor: \${errors.length} error(s) — run harness doctor\`, "warning");
    } catch {} // harness missing or doctor crashed — never block a session.
  });
}
`;

/** Slash-command shim: `.omp/prompts/<name>.md` → `/name` (09 D09-1; OMP prompts parse
 * `description` frontmatter and support $ARGUMENTS). Exported for the install bootstrap. */
export function promptShim(props: { name: string; description: string }): string {
  return `---
description: ${props.description}
---

${GENERATED_MARKER}
Invoke the \`${props.name}\` skill: read \`.agent/skills/${props.name}/SKILL.md\` and follow it exactly,
starting with its Preflight. Arguments: $ARGUMENTS
`;
}

/** Anti-pattern TTSR rules file, generated only when opt-in pattern: lines exist. */
function rulesFile(props: { regexes: string[] }): string {
  return `---
description: Anti-patterns from .agent/docs/standards/anti-patterns.md (auto-compiled)
condition: [${props.regexes.map((r) => JSON.stringify(r)).join(", ")}]
interruptMode: prose-only
---

${GENERATED_MARKER}
Matched output violates an anti-pattern. Read .agent/docs/standards/anti-patterns.md, point out the violation, and fix it.
`;
}

/**
 * OMP bridge planner (master §9.2 rows 1–7). Pure — string building only, no I/O.
 * Emits 2 symlinks, generated agents/instructions/config/hook (+ rules file only when
 * anti-pattern regexes exist), and the gitignore line unless commit_bridges.
 */
export const ompAdapter: PlatformAdapter = {
  id: "omp",
  dir: ".omp",
  plan(props: { ctx: ProjectContext }): BridgePlan {
    const { ctx } = props;
    const files: BridgePlan["files"] = [];

    for (const skill of [...ctx.skills].sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const role = typeof skill.frontmatter["harness_model_role"] === "string" ? (skill.frontmatter["harness_model_role"] as string) : null;
      const routed = (ROUTED_SKILLS as readonly string[]).includes(skill.name) || role !== null;
      const description = skill.frontmatter["description"];
      if (!routed || typeof description !== "string" || description === "") continue;
      files.push({
        path: `.omp/agents/${skill.name}.md`,
        content: agentFile({ name: skill.name, description, role }),
      });
    }

    for (const skill of [...ctx.skills].sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const description = skill.frontmatter["description"];
      if (typeof description !== "string" || description === "") continue;
      // On OMP the WATCHDOG advisor runs this skill automatically; a /harness-advisor prompt
      // would only collide with OMP's builtin /advisor in the command palette.
      if (skill.name === "harness-advisor") continue;
      // OMP ships its own /init — the harness init prompt is /harness-init on every platform.
      const fileName = skill.name === "init" ? "harness-init" : skill.name;
      files.push({ path: `.omp/prompts/${fileName}.md`, content: promptShim({ name: skill.name, description }) });
    }

    for (const rule of ctx.contextRules ?? []) {
      if (rule.when.length === 1) {
        files.push({
          path: `.omp/instructions/${rule.id}.instructions.md`,
          content: instructionsFile({ glob: rule.when[0] as string, inject: rule.inject }),
        });
      } else {
        rule.when.forEach((glob, n) => {
          files.push({
            path: `.omp/instructions/${rule.id}-${n}.instructions.md`,
            content: instructionsFile({ glob, inject: rule.inject }),
          });
        });
      }
    }

    files.push({ path: ".omp/config.yml", content: ompConfigFile({ advisor: ctx.manifest.models.advisor, tiers: ctx.manifest.models.tiers }) });
    if (ctx.manifest.models.advisor) {
      files.push({ path: ".omp/WATCHDOG.yml", content: watchdogFile({ cheapModel: ctx.manifest.models.tiers.cheap }) });
    }
    files.push({ path: ".omp/hooks/session-doctor.ts", content: HOOK_FILE });
    if (ctx.antiPatternRegexes.length > 0) {
      files.push({ path: ".omp/rules/anti-patterns.md", content: rulesFile({ regexes: ctx.antiPatternRegexes }) });
    }
    files.sort((a, b) => (a.path < b.path ? -1 : 1));

    return {
      symlinks: [
        { linkPath: ".omp/AGENTS.md", targetPath: ".agent/AGENTS.md" },
        { linkPath: ".omp/skills", targetPath: ".agent/skills" },
      ],
      files,
      gitignoreLines: ctx.manifest.platforms.commit_bridges === true ? [] : [".omp/"],
    };
  },
};
