prSections:
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me
  type: null

issuesSections:
- title: webapp-v2 (Edapt)
  filters: is:open repo:edapt-schools/webapp-v2
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me org:edapt-schools

repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60

defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: issues
  layout:

    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15

    issues:
      labels:
        width: 10
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: false
  refetchIntervalMinutes: 30

keybindings:
  universal: []
  issues: []
  prs: []
  branches: []

repoPaths: {
  "edapt-schools/*": "~/Desktop/Edapt/*",
  "edapt-schools/webapp-v2": "~/Desktop/Edapt/webapp-v2"
}

theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false

pager:
  diff: ""

confirmQuit: false
