require("items.apple")
require("items.menus")
require("items.aerospace_mode")
require("items.spaces_aero_and_icons")
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.spotify_media")
