import { describe, expect, test } from "bun:test";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { mkTmpProject, rmProject, runCli } from "../../test/helpers.ts";
import { contextFilesFor } from "./context.ts";

const RULES_YAML = `# GENERATED by harness sync — do not edit.
version: 1
rules:
  - id: std-backend
    when: ["convex/**"]
    inject:
      - docs/standards/backend/api.md
  - id: naming
    when: ["**/*.ts", "**/*.tsx"]
    inject:
      - docs/standards/naming-conventions.md
`;

function seeded(): string {
  const dir = mkTmpProject({ fixture: "initialized" });
  writeFileSync(join(dir, ".agent/context-rules.yaml"), RULES_YAML);
  return dir;
}

describe("context --for", () => {
  test("path token matches both rules in order", async () => {
    const dir = seeded();
    const r = await runCli({ argv: ["context", "--for", "add a convex mutation in convex/collections.ts"], cwd: dir });
    expect(r.code).toBe(0);
    expect(r.stdout).toBe("docs/standards/backend/api.md\ndocs/standards/naming-conventions.md");
    rmProject({ dir });
  });

  test("no match → note, exit 0", async () => {
    const dir = seeded();
    const r = await runCli({ argv: ["context", "--for", "tweak css"], cwd: dir });
    expect(r.stdout).toBe("(no matching context rules)");
    expect(r.code).toBe(0);
    rmProject({ dir });
  });

  test("word token hits the rule id segment", async () => {
    const dir = seeded();
    const r = await runCli({ argv: ["context", "--for", "backend cleanup"], cwd: dir });
    expect(r.stdout).toBe("docs/standards/backend/api.md");
    rmProject({ dir });
  });

  test("--files hint matches without task tokens", async () => {
    const dir = seeded();
    const r = await runCli({ argv: ["context", "--for", "x", "--files", "src/lib/date-utils.ts"], cwd: dir });
    expect(r.stdout).toBe("docs/standards/naming-conventions.md");
    rmProject({ dir });
  });

  test("absent context-rules.yaml → sync note, exit 0", async () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const r = await runCli({ argv: ["context", "--for", "anything at all"], cwd: dir });
    expect(r.stdout).toBe("(no context rules — run harness sync)");
    expect(r.code).toBe(0);
    rmProject({ dir });
  });
});

describe("contextFilesFor (C-05c wrapper)", () => {
  test("absent file → []", () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    expect(contextFilesFor({ root: dir, task: "convex/x.ts work" })).toEqual([]);
    rmProject({ dir });
  });
  test("delegates to matchContextRules", () => {
    const dir = seeded();
    expect(contextFilesFor({ root: dir, task: "backend work" })).toEqual(["docs/standards/backend/api.md"]);
    rmProject({ dir });
  });
});
