import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { parseFrontmatter } from "../lib/frontmatter.ts";
import { walk, writeFileAtomic } from "../lib/fsx.ts";
import { P } from "../lib/paths.ts";

/**
 * Derives a one-line description per D02-7: frontmatter `description` wins; else skip
 * headings, fenced blocks, blank, list and table lines; first remaining line, `> ` stripped.
 *
 * @param props.text - Standards file content.
 * @returns The description, or the "(first paragraph missing — add one)" sentinel.
 */
export function extractDescription(props: { text: string }): string {
  const fm = parseFrontmatter({ text: props.text });
  if (typeof fm.data["description"] === "string" && fm.data["description"] !== "") {
    return fm.data["description"] as string;
  }
  let inFence = false;
  for (const line of fm.body.split("\n")) {
    if (line.startsWith("```")) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const t = line.trim();
    if (t === "" || t.startsWith("#") || t.startsWith("- ") || t.startsWith("| ")) continue;
    return t.startsWith("> ") ? t.slice(2) : t;
  }
  return "(first paragraph missing — add one)";
}

/**
 * Builds the index.yml content (master §7.5, hand-emitted stable flow style per D02-8).
 *
 * @param props.root - Project root.
 * @returns The full index.yml text.
 */
export function buildIndex(props: { root: string }): string {
  const standardsAbs = join(props.root, P.standards);
  const files = existsSync(standardsAbs) ? walk({ root: standardsAbs }).filter((f) => f.endsWith(".md")) : [];

  const groups = new Map<string, Array<{ key: string; description: string; lines: number }>>();
  for (const file of files) {
    const text = readFileSync(join(standardsAbs, file), "utf8");
    const group = file.includes("/") ? (file.split("/")[0] as string) : "root";
    const key = (file.includes("/") ? file.slice(group.length + 1) : file).replace(/\.md$/, "");
    const lines = (text.match(/\n/g) ?? []).length;
    const entry = { key, description: extractDescription({ text }), lines };
    const arr = groups.get(group) ?? [];
    arr.push(entry);
    groups.set(group, arr);
  }

  const out: string[] = ["# GENERATED by harness index rebuild"];
  const groupNames = [...groups.keys()].filter((g) => g !== "root").sort();
  const ordered = groups.has("root") ? ["root", ...groupNames] : groupNames;
  if (ordered.length === 0) return `${out.join("\n")}\nroot: {}\n`;
  for (const group of ordered) {
    out.push(`${group}:`);
    for (const e of (groups.get(group) as Array<{ key: string; description: string; lines: number }>).sort((a, b) => (a.key < b.key ? -1 : 1))) {
      out.push(`  ${e.key}: { description: "${e.description.replaceAll('"', '\\"')}", lines: ${e.lines} }`);
    }
  }
  return `${out.join("\n")}\n`;
}

/**
 * `harness index rebuild` — writes docs/standards/index.yml and prints the path.
 * The output always parse-validates with the yaml package before writing.
 *
 * @param props.root - Project root.
 * @param props.stdout - Line sink.
 * @returns EXIT.OK.
 */
export function indexRebuild(props: { root: string; stdout: (s: string) => void }): number {
  const content = buildIndex({ root: props.root });
  parseYaml(content); // self-check: hand-emitted YAML must parse
  const rel = join(P.standards, "index.yml");
  writeFileAtomic({ path: join(props.root, rel), content });
  props.stdout(rel);
  return 0;
}
