import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { HarnessError } from "../lib/errors.ts";
import { parseFrontmatter } from "../lib/frontmatter.ts";
import { writeFileAtomic } from "../lib/fsx.ts";
import { headSha } from "../lib/git.ts";
import { loadManifest, validateManifest, DEFAULT_BUDGETS, type DependencyPin } from "../lib/manifest.ts";
import { AGENT_DIR, P } from "../lib/paths.ts";
import { loadTemplate } from "../lib/templateStore.ts";

const TEMPLATES = join(dirname(fileURLToPath(import.meta.url)), "..", "templates");
const BASE_VERSION = "0.1.0";

const TASKS_SKELETON = "## In Progress\n\n## Inbox\n\n## Recently Done\n";
const DEPS_GITIGNORE = "*\n!.gitignore\n!registry.md\n";
// Kept byte-identical to depsRegistry.serializeRegistry({ rows: [] }) — one format, two writers.
const REGISTRY_HEADER = `# Dependency Source Clones

> GENERATED by \`harness deps\` — clone directories are gitignored; this registry is committed.
> Skills read this table before specs/implementation to consult real source at the pinned version.

| package | version | repo | cloned_at_sha |
| --- | --- | --- | --- |
`;

function readTemplate(rel: string): string {
  return readFileSync(join(TEMPLATES, rel), "utf8");
}

function progressPath(root: string): string {
  return join(root, P.setupProgress);
}

function readProgress(root: string): string {
  try {
    return readFileSync(progressPath(root), "utf8");
  } catch {
    throw new HarnessError("init-incomplete", "No .agent/.setup-progress.md — install the harness first", {
      hint: "harness install",
    });
  }
}

/** Returns the recorded JSON data block for a phase, or null. */
function phaseData(progress: string, phase: number): Record<string, unknown> | null {
  const re = new RegExp(`### Phase ${phase}\\n\\\`\\\`\\\`json\\n([\\s\\S]*?)\\n\\\`\\\`\\\``);
  const m = progress.match(re);
  if (m === null) return null;
  return JSON.parse(m[1] as string) as Record<string, unknown>;
}

function phaseTicked(progress: string, phase: number): boolean {
  return new RegExp(`^- \\[x\\] Phase ${phase} —`, "m").test(progress);
}

/** Ticks a phase checkbox and records its data block (replacing any prior block). */
function recordPhase(root: string, phase: number, data: Record<string, unknown>): void {
  let progress = readProgress(root);
  progress = progress.replace(new RegExp(`^- \\[ \\] Phase ${phase} —`, "m"), `- [x] Phase ${phase} —`);
  const block = `### Phase ${phase}\n\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\``;
  const re = new RegExp(`### Phase ${phase}\\n\\\`\\\`\\\`json\\n[\\s\\S]*?\\n\\\`\\\`\\\``);
  progress = re.test(progress) ? progress.replace(re, block) : `${progress.trimEnd()}\n\n${block}\n`;
  writeFileAtomic({ path: progressPath(root), content: progress });
}

function requireKeys(phase: number, data: Record<string, unknown>, keys: Array<[string, "string" | "array" | "object"]>): void {
  for (const [key, kind] of keys) {
    const v = data[key];
    const ok =
      kind === "string" ? typeof v === "string" : kind === "array" ? Array.isArray(v) : typeof v === "object" && v !== null && !Array.isArray(v);
    if (!ok) throw new HarnessError("usage", `phase ${phase}: missing or invalid key \`${key}\` (expected ${kind})`);
  }
}

/** Wraps markdown content with verified_at frontmatter (sha "" → omitted). */
function withVerifiedAt(content: string, sha: string): string {
  const fm = sha === "" ? "" : `---\nverified_at: ${sha}\n---\n\n`;
  return `${fm}${content.trimEnd()}\n`;
}

/**
 * `harness install [--template <name>]` (CLI name; internally the init scaffold) — idempotent .agent/ skeleton creation (D5).
 * Fills gaps only. With a template: seeds win over embedded defaults (D-07-4) and structural
 * phase data is STAGED into the progress file with checkboxes unticked (D-07-1) — only
 * write-phase, validating as always, commits it.
 *
 * @param props.root - Project root.
 * @param props.template - Optional init-template name (loaded FIRST — not-found aborts early).
 * @param props.stdout - Line sink; created paths are printed.
 * @returns EXIT.OK.
 * @throws {HarnessError} "template-not-found" / "template-invalid" before any write.
 */
export function initScaffold(props: { root: string; template?: string; stdout: (s: string) => void }): number {
  const tpl = props.template !== undefined ? loadTemplate({ name: props.template }) : null;
  const skillsAbs = join(props.root, P.skills);
  const preExistingSkills = new Set(
    existsSync(skillsAbs)
      ? readdirSync(skillsAbs, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name)
      : [],
  );
  const created: string[] = [];
  const ensureDir = (rel: string): void => {
    const abs = join(props.root, rel);
    if (!existsSync(abs)) {
      mkdirSync(abs, { recursive: true });
      created.push(`${rel}/`);
    }
  };
  const ensureFile = (rel: string, content: string): void => {
    const abs = join(props.root, rel);
    if (!existsSync(abs)) {
      writeFileAtomic({ path: abs, content });
      created.push(rel);
    }
  };

  for (const dir of [P.product, P.standards, P.specs, P.decisions, P.sessionLog, P.skills, P.dependencies]) {
    ensureDir(dir);
  }
  const projectName = props.root.split("/").pop() ?? "project";
  ensureFile(P.agentsMd, readTemplate("agent/AGENTS.fallback.md").replaceAll("{{PROJECT}}", projectName));
  // Don't resurrect the progress file on an already-initialized project (finish deleted it).
  if (!existsSync(join(props.root, P.manifest))) {
    ensureFile(P.setupProgress, readTemplate("agent/setup-progress.md"));
  }
  ensureFile(P.tasks, TASKS_SKELETON);
  ensureFile(join(P.dependencies, ".gitignore"), DEPS_GITIGNORE);
  ensureFile(P.depsRegistry, REGISTRY_HEADER);

  // Copy embedded default skills, skipping any skill dir that already exists.
  const skillsSrc = join(TEMPLATES, "skills");
  for (const entry of readdirSync(skillsSrc, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dest = join(props.root, P.skills, entry.name);
    if (!existsSync(dest)) {
      cpSync(join(skillsSrc, entry.name), dest, { recursive: true });
      created.push(`${P.skills}/${entry.name}/`);
    }
  }

  if (tpl !== null) {
    // a. skills_seed overwrites the embedded defaults just copied — but never a dir that
    //    pre-existed this run (idempotent re-scaffold keeps project customizations).
    for (const skillName of tpl.skillsSeed) {
      if (preExistingSkills.has(skillName)) continue;
      const dest = join(props.root, P.skills, skillName);
      rmSync(dest, { recursive: true, force: true });
      cpSync(join(tpl.dir, "skills_seed", skillName), dest, { recursive: true });
      created.push(`skill ${skillName} (from template)`);
    }
    // b. standards_seed → docs/standards, mirrored paths, missing targets only.
    for (const rel of tpl.standardsSeed) {
      const dest = join(props.root, P.standards, rel);
      if (!existsSync(dest)) {
        mkdirSync(dirname(dest), { recursive: true });
        cpSync(join(tpl.dir, "standards_seed", rel), dest);
        created.push(`${P.standards}/${rel} (from template)`);
      }
    }
    // c+d. Stage prefilled phase data (unticked) + record the template name in frontmatter.
    if (existsSync(progressPath(props.root))) {
      let progress = readProgress(props.root);
      for (const key of Object.keys(tpl.template.prefilled).sort()) {
        const phase = Number(key);
        if (phaseData(progress, phase) !== null) continue; // never overwrite an existing block
        const data = (tpl.template.prefilled as Record<string, unknown>)[key];
        progress = `${progress.trimEnd()}\n\n### Phase ${phase}\n\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\`\n`;
      }
      if (!progress.startsWith("---\n")) {
        progress = `---\ntemplate: ${props.template as string}\n---\n\n${progress}`;
      }
      writeFileAtomic({ path: progressPath(props.root), content: progress });
    }
  }

  props.stdout(created.length > 0 ? created.map((c) => `created: ${c}`).join("\n") : "nothing to create — scaffold already complete");
  return 0;
}

/**
 * `harness init write-phase <n> --data <json>` — deterministic phase writers (D5).
 *
 * @param props.root - Project root.
 * @param props.phase - Phase number 1–9 (10 is completed by finish).
 * @param props.data - Parsed phase data (shape per phase table).
 * @param props.stdout - Line sink.
 * @returns EXIT.OK.
 * @throws {HarnessError} "usage" on bad phase/data; "init-incomplete" when prerequisites missing.
 */
export function initWritePhase(props: {
  root: string;
  phase: number;
  data: Record<string, unknown>;
  stdout: (s: string) => void;
}): number {
  const { root, phase, data } = props;
  if (!Number.isInteger(phase) || phase < 1 || phase > 10) {
    throw new HarnessError("usage", `invalid phase ${phase} (expected 1–9)`);
  }
  if (phase === 10) {
    throw new HarnessError("usage", "phase 10 is completed by `harness init finish`");
  }
  readProgress(root); // asserts scaffold ran
  const sha = headSha({ root });
  const wrote: string[] = [];

  switch (phase) {
    case 1:
      requireKeys(1, data, [["project", "string"], ["description", "string"], ["language", "string"], ["repo_type", "string"]]);
      break;
    case 2:
      requireKeys(2, data, [["purpose", "string"], ["team", "string"]]);
      break;
    case 3: {
      requireKeys(3, data, [["domains", "array"]]);
      for (const d of data["domains"] as unknown[]) {
        if (typeof d !== "string" || !/^[a-z][a-z0-9-]*$/.test(d)) {
          throw new HarnessError("usage", `phase 3: domain ${JSON.stringify(d)} must be kebab-case`);
        }
        const dir = join(root, P.standards, d);
        mkdirSync(dir, { recursive: true });
        const readme = join(dir, "README.md");
        if (!existsSync(readme)) writeFileSync(readme, `# ${d} standards\n`);
        wrote.push(`${P.standards}/${d}/`);
      }
      break;
    }
    case 4: {
      requireKeys(4, data, [["tech_stack_md", "string"]]);
      const path = join(root, P.product, "tech-stack.md");
      writeFileAtomic({ path, content: withVerifiedAt(data["tech_stack_md"] as string, sha) });
      wrote.push(`${P.product}/tech-stack.md`);
      break;
    }
    case 5: {
      requireKeys(5, data, [["dev_processes_md", "string"], ["env_vars", "array"]]);
      writeFileAtomic({
        path: join(root, P.product, "dev-processes.md"),
        content: withVerifiedAt(data["dev_processes_md"] as string, sha),
      });
      wrote.push(`${P.product}/dev-processes.md`);
      const vars = data["env_vars"] as Array<Record<string, unknown>>;
      if (vars.length > 0) {
        const rows = vars.map((v) => {
          if (typeof v["name"] !== "string" || typeof v["desc"] !== "string") {
            throw new HarnessError("usage", "phase 5: env_vars entries need string `name` and `desc`");
          }
          const required = v["required"] === false ? "no" : "yes";
          return `| ${v["name"] as string} | ${required} | ${v["desc"] as string} |`;
        });
        writeFileAtomic({
          path: join(root, P.envManifest),
          content: `# Environment Variables\n\n| VAR | required | description |\n|---|---|---|\n${rows.join("\n")}\n`,
        });
        wrote.push(P.envManifest);
      }
      break;
    }
    case 6: {
      requireKeys(6, data, [["dependencies", "array"]]);
      const deps = data["dependencies"] as Array<Record<string, unknown>>;
      const rows: string[] = [];
      for (const dep of deps) {
        if (typeof dep["package"] !== "string" || typeof dep["version"] !== "string" || typeof dep["repo"] !== "string") {
          throw new HarnessError("usage", "phase 6: dependencies entries need string `package`, `version`, `repo`");
        }
        rows.push(`| ${dep["package"] as string} | ${dep["version"] as string} | ${dep["repo"] as string} | (not cloned) |`);
      }
      if (rows.length > 0) {
        const existing = existsSync(join(root, P.depsRegistry)) ? readFileSync(join(root, P.depsRegistry), "utf8") : REGISTRY_HEADER;
        writeFileAtomic({ path: join(root, P.depsRegistry), content: `${existing.trimEnd()}\n${rows.join("\n")}\n` });
        wrote.push(P.depsRegistry);
      }
      break;
    }
    case 7: {
      requireKeys(7, data, [["platforms", "object"], ["workflow", "object"], ["modules", "object"]]);
      const progress = readProgress(root);
      const p1 = phaseData(progress, 1);
      if (p1 === null) throw new HarnessError("init-incomplete", "phase 7 requires phase 1 data — run write-phase 1 first");
      const p6 = phaseData(progress, 6);
      if (p6 === null) throw new HarnessError("init-incomplete", "phase 7 requires phase 6 data — run write-phase 6 first (empty dependencies list is fine)");
      const p3 = phaseData(progress, 3);
      const templateName = parseFrontmatter({ text: progress }).data["template"];
      const manifestValue = {
        schema_version: "1.0",
        project: p1["project"],
        description: p1["description"],
        harness: {
          base_version: BASE_VERSION,
          ...(typeof templateName === "string" && templateName !== "" ? { template: templateName } : {}),
        },
        platforms: data["platforms"],
        workflow: data["workflow"],
        modules: data["modules"],
        standards_domains: (p3?.["domains"] as string[] | undefined) ?? [],
        dependencies: (p6["dependencies"] as DependencyPin[] | undefined) ?? [],
        doctor: { budgets: { ...DEFAULT_BUDGETS }, stale_spec_days: 14 },
        ...(p1["repo_type"] === "bare-git-worktrees" ? { repo: { type: "bare-git-worktrees" } } : {}),
      };
      const { manifest } = validateManifest({ value: manifestValue });
      writeFileAtomic({ path: join(root, P.manifest), content: `${JSON.stringify(manifest, null, 2)}\n` });
      wrote.push(P.manifest);
      break;
    }
    case 8: {
      requireKeys(8, data, [["naming_conventions_md", "string"]]);
      const content = data["naming_conventions_md"] as string;
      if (content.trim() !== "") {
        writeFileAtomic({ path: join(root, P.standards, "naming-conventions.md"), content: `${content.trimEnd()}\n` });
        wrote.push(`${P.standards}/naming-conventions.md`);
      }
      break;
    }
    case 9: {
      requireKeys(9, data, [["mission_md", "string"]]);
      writeFileAtomic({ path: join(root, P.product, "mission.md"), content: `${(data["mission_md"] as string).trimEnd()}\n` });
      wrote.push(`${P.product}/mission.md`);
      if (typeof data["roadmap_md"] === "string" && (data["roadmap_md"] as string).trim() !== "") {
        writeFileAtomic({ path: join(root, P.product, "roadmap.md"), content: `${(data["roadmap_md"] as string).trimEnd()}\n` });
        wrote.push(`${P.product}/roadmap.md`);
      }
      break;
    }
  }

  recordPhase(root, phase, data);
  props.stdout(wrote.length > 0 ? wrote.map((w) => `wrote: ${w}`).join("\n") : `recorded phase ${phase}`);
  return 0;
}

/**
 * `harness init status` — prints the checklist + which phases have recorded data.
 *
 * @param props.root - Project root.
 * @param props.stdout - Line sink.
 * @returns EXIT.OK.
 */
export function initStatus(props: { root: string; stdout: (s: string) => void }): number {
  const progress = readProgress(props.root);
  const lines = progress.split("\n").filter((l) => l.startsWith("- ["));
  const out = lines.map((l) => {
    const m = l.match(/Phase (\d+)/);
    const n = m !== null ? Number(m[1]) : 0;
    const hasData = phaseData(progress, n) !== null;
    return hasData && l.startsWith("- [ ]") ? `${l} — prefilled (confirm or edit)` : l;
  });
  props.stdout(out.join("\n"));
  return 0;
}

/**
 * `harness init finish` — validates phases 1–9, writes the post-init AGENTS.md,
 * deletes the progress file, prints next steps.
 *
 * @param props.root - Project root.
 * @param props.stdout - Line sink.
 * @returns EXIT.OK.
 * @throws {HarnessError} "init-incomplete" listing missing phases or manifest.
 */
export function initFinish(props: { root: string; stdout: (s: string) => void }): number {
  const progress = readProgress(props.root);
  const missing: number[] = [];
  for (let n = 1; n <= 9; n++) {
    if (!phaseTicked(progress, n)) missing.push(n);
  }
  if (missing.length > 0) {
    throw new HarnessError("init-incomplete", `phases not completed: ${missing.join(", ")}`, {
      hint: `harness init write-phase ${missing[0]} --data <json>`,
    });
  }
  const { manifest } = loadManifest({ root: props.root }); // throws not-initialized if phase 7 skipped writing

  writeFileAtomic({
    path: join(props.root, P.agentsMd),
    content: readTemplate("agent/AGENTS.post-init.md").replaceAll("{{PROJECT}}", manifest.project),
  });

  // Guide + setup report (09): the guide is written ONCE (developer/agent-maintained after);
  // the setup report is regenerated on every finish (it reflects the just-confirmed config).
  const moduleNames = Object.entries(manifest.modules);
  const modulesOn = moduleNames.filter(([, v]) => v === true).map(([k]) => k).join(", ") || "(none)";
  const modulesOff = moduleNames.filter(([, v]) => v !== true).map(([k]) => k).join(", ") || "(none)";
  const domains = manifest.standards_domains.join(", ") || "(none)";
  const guidePath = join(props.root, P.docs, "harness-guide.md");
  if (!existsSync(guidePath)) {
    writeFileAtomic({
      path: guidePath,
      content: readTemplate("agent/harness-guide.md")
        .replaceAll("{{PROJECT}}", manifest.project)
        .replaceAll("{{DOMAINS}}", domains)
        .replaceAll("{{MODULES_ON}}", modulesOn)
        .replaceAll("{{MODULES_OFF}}", modulesOff),
    });
  }
  const sha = headSha({ root: props.root });
  writeFileAtomic({
    path: join(props.root, P.docs, "setup-report.md"),
    content: [
      `# Harness Setup Report — ${manifest.project}`,
      `> Written by \`harness init finish\`${sha !== "" ? ` at commit ${sha.slice(0, 7)}` : ""}. Review it, then ask the`,
      "> agent questions, correct errors, or request changes — everything here is adjustable.",
      "",
      "## What was configured",
      "",
      `- **Platforms**: ${manifest.platforms.active.join(", ")} — bridges generated by \`harness sync\``,
      `- **Workflow**: ${manifest.workflow.default_tier}, importance ${manifest.workflow.importance}, commit mode \`${manifest.workflow.commit_mode}\``,
      `- **Standards domains**: ${domains}`,
      `- **Modules on**: ${modulesOn}`,
      `- **Modules off**: ${modulesOff}`,
      `- **Pinned dependencies**: ${manifest.dependencies.length > 0 ? manifest.dependencies.map((d) => d.package).join(", ") : "(none)"}`,
      "",
      "## How agents will use this harness",
      "",
      "- Every session starts with `harness doctor` (auto via the platform hooks) and `harness state`.",
      "- Workflows are skills in `.agent/skills/` — invocable as slash commands (`/harness-init` on",
      "  Claude Code, `/init` on OMP; `/dev-spec`, `/sync-spec`, `/commit`, …) or by natural language.",
      "- Before touching code, agents query the code map (`harness context --for \"<task>\"`) to load",
      "  exactly the standards that govern the files they will change.",
      "- Learnings flow back into the harness (see `docs/harness-guide.md`, \"Where knowledge goes\"),",
      "  and `harness sync` recompiles the map after standards change.",
      "- `/commit` runs the project's commit checklist",
      "  (`.agent/skills/commit/references/commit-checklist.md`) before anything ships upstream.",
      "",
      "## What to review now",
      "",
      "- `docs/harness-guide.md` — how this harness is organized",
      "- `docs/standards/` — the practices recorded for this project (discovery findings below)",
      "- `docs/standards/naming-conventions.md` — the naming rules agents will enforce",
      "- `.agent/skills/commit/references/commit-checklist.md` — your pre-push gate",
      "",
      "## What discovery found",
      "",
      "_(appended by the init skill after its full-codebase discovery pass)_",
      "",
    ].join("\n"),
  });

  rmSync(progressPath(props.root), { force: true });
  props.stdout(
    [
      `harness initialized for ${manifest.project}`,
      `setup report: ${P.docs}/setup-report.md  ← read this`,
      "next steps:",
      "  harness sync      # generate platform bridges",
      "  harness doctor    # verify health",
      "  harness state     # see project state",
    ].join("\n"),
  );
  return 0;
}
