import { describe, expect, test } from "bun:test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { mkTmpProject, rmProject, runCli } from "../../test/helpers.ts";

describe("harness state", () => {
  test("golden state.md for the initialized fixture (no git → SHA unknown)", async () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const r = await runCli({ argv: ["state"], cwd: dir });
    expect(r.code).toBe(0);
    const written = readFileSync(join(dir, ".agent/docs/state.md"), "utf8");
    expect(written).toBe(
      [
        "# Project State",
        "> GENERATED by `harness state` — do not edit. SHA: unknown",
        "",
        "## Active specs",
        "",
        "(none)",
        "",
        "## Tasks",
        "",
        "## In Progress",
        "",
        "- Wire the filter panel",
        "",
        "## Inbox",
        "",
        "- Investigate slow test startup",
        "",
        "## Recent sessions",
        "",
        "(none)",
        "",
        "## Doctor",
        "",
        "0 errors, 0 warnings at last run",
        "",
      ].join("\n"),
    );
    expect(r.stdout).toBe(written.trimEnd());
    rmProject({ dir });
  });

  test("open spec renders open/total checkbox counts", async () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const specDir = join(dir, ".agent/docs/specs/2026-08-01-demo");
    mkdirSync(specDir, { recursive: true });
    writeFileSync(join(specDir, "spec.md"), "---\nstatus: in-progress\nspec_id: 2026-08-01-demo\n---\n\n# Demo\n");
    writeFileSync(
      join(specDir, "spec-tasks.md"),
      "## T1\n- [x] a\n- [x] b\n## T2\n- [ ] c\n- [ ] d\n- [ ] e\n",
    );
    const r = await runCli({ argv: ["state"], cwd: dir });
    expect(r.stdout).toContain("- 2026-08-01-demo — in-progress — 3 open / 5 total tasks");
    rmProject({ dir });
  });

  test("disabled modules omit their sections", async () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const manifestPath = join(dir, ".agent/manifest.json");
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    manifest.modules.session_log = false;
    manifest.modules.tasks = false;
    writeFileSync(manifestPath, JSON.stringify(manifest));
    const r = await runCli({ argv: ["state"], cwd: dir });
    expect(r.stdout).not.toContain("## Recent sessions");
    expect(r.stdout).not.toContain("## Tasks");
    expect(r.stdout).toContain("## Active specs");
    rmProject({ dir });
  });
});
