import { join } from "node:path";
import type { DoctorCheck } from "./doctor.ts";
import { buildCheckContext, runDoctor } from "./doctor.ts";
import { writeFileAtomic } from "../lib/fsx.ts";
import { loadManifest } from "../lib/manifest.ts";
import { Reporter } from "../lib/output.ts";
import { P } from "../lib/paths.ts";
import { parseFrontmatter } from "../lib/frontmatter.ts";

/** Extracts a named `## <name>` section (heading + content up to the next `## `). */
function section(text: string, name: string): string | null {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => l.trim() === `## ${name}`);
  if (start === -1) return null;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if ((lines[i] as string).startsWith("## ")) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n").trimEnd();
}

/**
 * Builds the state.md content from files the CLI can read (never from model output).
 *
 * @param props.root - Project root.
 * @param props.checks - Doctor registry, run silently for the Doctor summary line.
 * @returns The full state.md text.
 */
export function buildState(props: { root: string; checks: DoctorCheck[] }): string {
  const { manifest } = loadManifest({ root: props.root });
  const ctx = buildCheckContext({ root: props.root, manifest });
  const out: string[] = [];
  out.push("# Project State");
  out.push(`> GENERATED by \`harness state\` — do not edit. SHA: ${ctx.headSha === "" ? "unknown" : ctx.headSha}`);
  out.push("");

  if (manifest.modules.specs) {
    out.push("## Active specs", "");
    const specDirs = [...new Set(
      ctx.listFiles(P.specs)
        .map((f) => f.split("/").slice(0, 4).join("/"))
        .filter((d) => d.split("/").length === 4),
    )].sort();
    const lines: string[] = [];
    for (const dir of specDirs) {
      const specMd = ctx.read(`${dir}/spec.md`);
      if (specMd === null) continue;
      const status = parseFrontmatter({ text: specMd }).data["status"];
      if (status === "done") continue;
      const tasks = ctx.read(`${dir}/spec-tasks.md`) ?? "";
      const open = (tasks.match(/- \[ \]/g) ?? []).length;
      const total = open + (tasks.match(/- \[x\]/gi) ?? []).length;
      lines.push(`- ${dir.split("/").pop()} — ${String(status ?? "draft")} — ${open} open / ${total} total tasks`);
    }
    out.push(lines.length > 0 ? lines.join("\n") : "(none)", "");
  }

  if (manifest.modules.tasks) {
    const tasksMd = ctx.read(P.tasks);
    if (tasksMd !== null) {
      out.push("## Tasks", "");
      for (const name of ["In Progress", "Inbox"]) {
        const s = section(tasksMd, name);
        if (s !== null) out.push(s, "");
      }
    }
  }

  if (manifest.modules.session_log) {
    out.push("## Recent sessions", "");
    const logFiles = ctx.listFiles(P.sessionLog).filter((f) => f.endsWith(".log.md")).sort().reverse();
    const headlines: string[] = [];
    for (const file of logFiles) {
      if (headlines.length >= 3) break;
      const text = ctx.read(file) ?? "";
      const entries = text.split("\n").filter((l) => l.startsWith("## ")).reverse();
      for (const e of entries) {
        if (headlines.length >= 3) break;
        headlines.push(`- ${e.slice(3)}`);
      }
    }
    out.push(headlines.length > 0 ? headlines.join("\n") : "(none)", "");
  }

  const silent = new Reporter({ json: true, write: () => {} });
  runDoctor({ root: props.root, checks: props.checks, reporter: silent });
  const errors = silent.items.filter((i) => i.level === "error").length;
  const warns = silent.items.filter((i) => i.level === "warn").length;
  out.push("## Doctor", "", `${errors} errors, ${warns} warnings at last run`);
  return `${out.join("\n")}\n`;
}

/**
 * `harness state` — regenerates .agent/docs/state.md and prints it (skills read stdout).
 *
 * @param props.root - Project root.
 * @param props.checks - Doctor registry.
 * @param props.stdout - Line sink.
 * @returns EXIT.OK.
 */
export function stateCommand(props: {
  root: string;
  checks: DoctorCheck[];
  stdout: (s: string) => void;
}): number {
  const content = buildState({ root: props.root, checks: props.checks });
  writeFileAtomic({ path: join(props.root, P.state), content });
  props.stdout(content.trimEnd());
  return 0;
}
