import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { EXIT, HarnessError } from "../lib/errors.ts";
import { walk, writeFileAtomic } from "../lib/fsx.ts";
import { headSha } from "../lib/git.ts";
import { loadManifest } from "../lib/manifest.ts";
import { checkPath, parseNamingRules, type NamingRule } from "../lib/namingRules.ts";
import type { Reporter } from "../lib/output.ts";
import { AGENT_DIR, P } from "../lib/paths.ts";

interface DirNode {
  dirs: Map<string, DirNode>;
  files: string[]; // basenames
}

function insert(node: DirNode, segments: string[]): void {
  if (segments.length === 1) {
    node.files.push(segments[0] as string);
    return;
  }
  const head = segments[0] as string;
  let child = node.dirs.get(head);
  if (child === undefined) {
    child = { dirs: new Map(), files: [] };
    node.dirs.set(head, child);
  }
  insert(child, segments.slice(1));
}

/** Loads the naming rules for a project; [] when the file is absent. Parse errors propagate. */
export function loadNamingRules(props: { root: string }): NamingRule[] {
  const path = join(props.root, P.standards, "naming-conventions.md");
  if (!existsSync(path)) return [];
  return parseNamingRules({ text: readFileSync(path, "utf8") });
}

/**
 * Builds directory-structure.md content: annotated workspace + harness trees plus the
 * naming rule summary (proposal §18.7; golden-pinned; "Recently Added" dropped — needs
 * wall-clock dates).
 *
 * @param props.root - Project root.
 * @param props.project - Project name for the workspace tree root label.
 * @param props.rules - Parsed naming rules ([] → no annotations).
 * @param props.headSha - Current HEAD sha ("" → "unknown" in the provenance line, D02-4).
 * @returns The full directory-structure.md text.
 */
export function buildStruct(props: {
  root: string;
  project: string;
  rules: NamingRule[];
  headSha: string;
}): string {
  // .agent/dependencies metadata is walked but never rendered (clone-adjacent noise).
  const files = walk({ root: props.root }).filter((f) => !f.startsWith(`${AGENT_DIR}/dependencies/`));
  const workspace: DirNode = { dirs: new Map(), files: [] };
  const harness: DirNode = { dirs: new Map(), files: [] };
  for (const f of files) {
    if (f.startsWith(`${AGENT_DIR}/`)) insert(harness, f.slice(AGENT_DIR.length + 1).split("/"));
    else insert(workspace, f.split("/"));
  }

  const render = (label: string, node: DirNode, basePath: string): string[] => {
    const out = [`${label}/`];
    const visit = (n: DirNode, prefix: string, dirPath: string): void => {
      const dirNames = [...n.dirs.keys()].sort();
      const fileNames = [...n.files].sort();
      const entries: Array<{ name: string; isDir: boolean }> = [
        ...dirNames.map((name) => ({ name, isDir: true })),
        ...fileNames.map((name) => ({ name, isDir: false })),
      ];
      entries.forEach((entry, i) => {
        const isLast = i === entries.length - 1;
        const connector = isLast ? "└── " : "├── ";
        const childPath = dirPath === "" ? entry.name : `${dirPath}/${entry.name}`;
        if (entry.isDir) {
          const child = n.dirs.get(entry.name) as DirNode;
          const ids = new Set<string>();
          for (const f of child.files) {
            for (const id of checkPath({ path: `${childPath}/${f}`, rules: props.rules }).matched) ids.add(id);
          }
          const annotation = ids.size > 0 ? `  ← ${[...ids].sort().map((id) => `[→ ${id}]`).join(" ")}` : "";
          out.push(`${prefix}${connector}${entry.name}/${annotation}`);
          visit(child, prefix + (isLast ? "    " : "│   "), childPath);
        } else {
          const result = checkPath({ path: childPath, rules: props.rules });
          const annotation = result.ok ? "" : `  ← ✗ violates ${result.matched[0]}`;
          out.push(`${prefix}${connector}${entry.name}${annotation}`);
        }
      });
    };
    visit(node, "", basePath);
    return out;
  };

  const workspaceTree = render(props.project, workspace, "");
  const harnessTree = render(AGENT_DIR, harness, AGENT_DIR);

  const summary =
    props.rules.length === 0
      ? ["(no naming rules — populate naming-conventions.md)"]
      : [
          "| Scope | Rule ID | Convention |",
          "|---|---|---|",
          ...props.rules.map((r) => `| \`${r.scope.join(", ")}\` | ${r.id} | ${r.description} |`),
        ];

  return [
    `# Directory Structure — ${props.project}`,
    "> GENERATED by `harness struct`. Do not edit manually.",
    "> See also: naming-conventions.md — full rule definitions and regex patterns.",
    `> Last updated by harness struct (SHA: ${props.headSha === "" ? "unknown" : props.headSha})`,
    "",
    "## Workspace",
    "",
    "```",
    ...workspaceTree,
    "```",
    "",
    "## Agent Harness Structure",
    "",
    "```",
    ...harnessTree,
    "```",
    "",
    "## Naming Rule Summary",
    "",
    ...summary,
  ].join("\n") + "\n";
}

/**
 * `harness struct` — regenerates directory-structure.md. `--check` validates only.
 *
 * @param props.root - Project root.
 * @param props.check - Validate without writing.
 * @param props.reporter - Sink for --check findings.
 * @param props.stdout - Line sink (written path).
 * @returns EXIT.OK, or EXIT.FINDINGS when --check found violations.
 * @throws {HarnessError} "naming-rules-invalid" when the rules block is unparseable.
 */
export function structCommand(props: {
  root: string;
  check: boolean;
  reporter: Reporter;
  stdout: (s: string) => void;
}): number {
  let rules: NamingRule[];
  try {
    rules = loadNamingRules({ root: props.root });
  } catch (e) {
    if (e instanceof HarnessError) {
      throw new HarnessError(e.code, e.message, { hint: ".agent/docs/standards/naming-conventions.md" });
    }
    throw e;
  }

  if (props.check) {
    const files = walk({ root: props.root }).filter((f) => !f.startsWith(`${AGENT_DIR}/dependencies/`));
    let violations = 0;
    for (const f of files) {
      const result = checkPath({ path: f, rules });
      if (!result.ok) {
        violations++;
        const rule = rules.find((r) => r.id === result.matched[0]);
        props.reporter.error(`${f} violates ${result.matched[0]} (${rule?.description ?? ""})`, result.matched[0]);
      }
    }
    if (violations === 0) props.reporter.ok("no naming violations");
    return violations > 0 ? EXIT.FINDINGS : EXIT.OK;
  }

  const { manifest } = loadManifest({ root: props.root });
  const content = buildStruct({
    root: props.root,
    project: manifest.project,
    rules,
    headSha: headSha({ root: props.root }),
  });
  const rel = join(P.standards, "directory-structure.md");
  writeFileAtomic({ path: join(props.root, rel), content });
  props.stdout(rel);
  return 0;
}
