import { existsSync, lstatSync, readFileSync, readdirSync, rmSync, rmdirSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { EXIT, HarnessError } from "../lib/errors.ts";
import { parseFrontmatter } from "../lib/frontmatter.ts";
import { ensureSymlink, sha256, walk, writeFileAtomic } from "../lib/fsx.ts";
import { headSha } from "../lib/git.ts";
import { loadManifest, type HarnessManifest } from "../lib/manifest.ts";
import { parseNamingRules } from "../lib/namingRules.ts";
import type { Reporter } from "../lib/output.ts";
import { AGENT_DIR, P } from "../lib/paths.ts";
import { loadSyncManifest, saveSyncManifest, type SyncEntry } from "../lib/syncManifest.ts";
import { claudeAdapter, CLAUDE_SETTINGS_FRAGMENT } from "../platforms/claude.ts";
import { ompAdapter } from "../platforms/omp.ts";
import type { ContextRule, PlatformAdapter, PlatformId, ProjectContext, SkillInfo } from "../platforms/types.ts";

/** Adapter registry — the single place platform.ts and sync share. */
export const ADAPTERS: Record<PlatformId, PlatformAdapter> = { omp: ompAdapter, claude: claudeAdapter };

/** Paths applied via mergeManagedJson instead of whole-file D10 hashing. */
export const MERGE_PATHS = new Set([".claude/settings.json"]);

const GITIGNORE_OPEN = "# >>> harness (managed by `harness sync`) >>>";
const GITIGNORE_CLOSE = "# <<< harness <<<";

/**
 * Compiles context rules from standards inventory + naming scopes (master §7.2). Pure.
 *
 * @param props.manifest - Loaded manifest (standards_domains gives domain order).
 * @param props.standards - Every docs/standards file: .agent-relative path + parsed applies_to.
 * @param props.namingScopes - Union input from naming rules block scopes; null when the module
 *   is off or the file is absent.
 * @returns Ordered rules plus the exact context-rules.yaml text (byte-stable) and warnings.
 */
export function buildContextRules(props: {
  manifest: HarnessManifest;
  standards: Array<{ path: string; appliesTo: string[] }>;
  namingScopes: string[] | null;
}): { rules: ContextRule[]; yaml: string; warnings: string[] } {
  const rules: ContextRule[] = [];
  const warnings: string[] = [];

  for (const domain of props.manifest.standards_domains) {
    const domainPrefix = `docs/standards/${domain}/`;
    const files = props.standards
      .filter((s) => s.path.startsWith(domainPrefix) && s.path.endsWith(".md"))
      .sort((a, b) => (a.path < b.path ? -1 : 1));
    const inject = files.map((f) => f.path);
    if (inject.length === 0) continue; // empty domain — skip silently
    const when = [...new Set(files.flatMap((f) => f.appliesTo))].sort();
    if (when.length === 0) {
      warnings.push(`domain ${domain} has no applies_to globs — rule omitted (add applies_to frontmatter)`);
      continue;
    }
    rules.push({ id: `std-${domain}`, when, inject });
  }

  if (props.namingScopes !== null && props.namingScopes.length > 0) {
    rules.push({
      id: "naming",
      when: [...new Set(props.namingScopes)].sort(),
      inject: ["docs/standards/naming-conventions.md"],
    });
  }

  const lines = [
    "# GENERATED by harness sync — do not edit. Source: standards folders + naming rule scopes.",
    "version: 1",
  ];
  if (rules.length === 0) {
    lines.push("rules: []");
  } else {
    lines.push("rules:");
    for (const rule of rules) {
      lines.push(`  - id: ${rule.id}`);
      lines.push(`    when: [${rule.when.map((w) => JSON.stringify(w)).join(", ")}]`);
      lines.push("    inject:");
      for (const path of rule.inject) lines.push(`      - ${path}`);
    }
  }
  return { rules, yaml: `${lines.join("\n")}\n`, warnings };
}

/**
 * Loads everything adapters need. The ONLY I/O gateway for planning (adapters stay pure).
 *
 * @param props.root - Absolute project root.
 * @returns Fully-populated ProjectContext plus compilation warnings for the reporter.
 */
export function loadProjectContext(props: { root: string }): {
  ctx: ProjectContext;
  warnings: string[];
} {
  const { manifest } = loadManifest({ root: props.root });

  const skills: SkillInfo[] = [];
  const skillsAbs = join(props.root, P.skills);
  if (existsSync(skillsAbs)) {
    for (const entry of readdirSync(skillsAbs, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      if (!entry.isDirectory()) continue;
      const skillMd = join(skillsAbs, entry.name, "SKILL.md");
      if (!existsSync(skillMd)) continue;
      const { data } = parseFrontmatter({ text: readFileSync(skillMd, "utf8") });
      skills.push({
        name: typeof data["name"] === "string" && data["name"] !== "" ? (data["name"] as string) : entry.name,
        dir: `${P.skills}/${entry.name}`,
        frontmatter: data,
      });
    }
  }

  const standardsAbs = join(props.root, P.standards);
  const standardsFiles = existsSync(standardsAbs)
    ? walk({ root: standardsAbs }).map((f) => `docs/standards/${f}`)
    : [];
  const standards = standardsFiles.map((path) => {
    const text = readFileSync(join(props.root, AGENT_DIR, path), "utf8");
    const appliesTo = parseFrontmatter({ text }).data["applies_to"];
    return { path, appliesTo: Array.isArray(appliesTo) ? (appliesTo as string[]) : [] };
  });

  let namingScopes: string[] | null = null;
  const namingPath = join(standardsAbs, "naming-conventions.md");
  if (manifest.modules.naming_conventions && existsSync(namingPath)) {
    try {
      namingScopes = [...new Set(parseNamingRules({ text: readFileSync(namingPath, "utf8") }).flatMap((r) => r.scope))];
    } catch {
      namingScopes = null; // unparseable rules block — naming-violations check owns reporting
    }
  }

  const antiPatternRegexes: string[] = [];
  const apPath = join(standardsAbs, "anti-patterns.md");
  if (existsSync(apPath)) {
    for (const line of readFileSync(apPath, "utf8").split("\n")) {
      const m = line.match(/^ {2}pattern: (.+)$/);
      if (m !== null) antiPatternRegexes.push((m[1] as string).trim());
    }
  }

  const built = buildContextRules({ manifest, standards, namingScopes });
  return {
    ctx: {
      root: props.root,
      manifest,
      skills,
      standardsFiles,
      contextRules: built.rules,
      antiPatternRegexes,
    },
    warnings: built.warnings,
  };
}

/**
 * Merges the managed settings fragment into a user-owned JSON file, touching ONLY the keys sync
 * manages (D10). Managed today: the one hooks.SessionStart entry whose command is
 * "harness doctor". Everything else is preserved.
 *
 * @param props.existingText - Current file text, or null when the file does not exist.
 * @param props.fragment - The managed fragment (CLAUDE_SETTINGS_FRAGMENT shape).
 * @returns merged: full new file text, or null when no write is needed; conflict: set instead
 *   when existing is not parseable JSON — caller reports, never writes.
 */
export function mergeManagedJson(props: {
  existingText: string | null;
  fragment: Record<string, unknown>;
}): { merged: string | null; conflict?: string } {
  const stringify = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
  if (props.existingText === null) return { merged: stringify(props.fragment) };

  let obj: Record<string, unknown>;
  try {
    obj = JSON.parse(props.existingText) as Record<string, unknown>;
    if (typeof obj !== "object" || obj === null || Array.isArray(obj)) throw new Error("not an object");
  } catch {
    return { merged: null, conflict: "not valid JSON — fix or delete it, then re-run harness sync" };
  }

  const hooks = (obj["hooks"] ??= {}) as Record<string, unknown>;
  if (hooks["SessionStart"] === undefined) hooks["SessionStart"] = [];
  const sessionStart = hooks["SessionStart"];
  if (!Array.isArray(sessionStart)) {
    return { merged: null, conflict: "hooks.SessionStart is not an array — fix it, then re-run harness sync" };
  }
  const hasDoctor = sessionStart.some((entry) => {
    const inner = (entry as Record<string, unknown>)?.["hooks"];
    return Array.isArray(inner) && inner.some((h) => (h as Record<string, unknown>)?.["command"] === "harness doctor");
  });
  if (!hasDoctor) {
    const fragmentHooks = (props.fragment["hooks"] as Record<string, unknown>)["SessionStart"] as unknown[];
    sessionStart.push(...fragmentHooks);
  }
  const merged = stringify(obj);
  return { merged: merged === props.existingText ? null : merged };
}

/**
 * Rewrites the managed marker block in the project .gitignore, preserving user lines byte-exact.
 *
 * @param props.existingText - Current .gitignore text or null.
 * @param props.lines - Desired managed lines (caller sorts them).
 * @returns New full text, or null when no change is needed.
 */
export function updateGitignoreBlock(props: { existingText: string | null; lines: string[] }): string | null {
  const block =
    props.lines.length > 0 ? `${GITIGNORE_OPEN}\n${props.lines.join("\n")}\n${GITIGNORE_CLOSE}\n` : null;

  if (props.existingText === null) {
    return block; // null lines + null file → null (no change)
  }
  const text = props.existingText;
  const open = text.indexOf(GITIGNORE_OPEN);
  if (open === -1) {
    if (block === null) return null;
    const sep = text === "" || text.endsWith("\n\n") ? "" : text.endsWith("\n") ? "\n" : "\n\n";
    return `${text}${sep}${block}`;
  }
  const close = text.indexOf(GITIGNORE_CLOSE, open);
  const blockEnd = close === -1 ? text.length : close + GITIGNORE_CLOSE.length + 1;
  const before = text.slice(0, open);
  const after = text.slice(Math.min(blockEnd, text.length));
  const next = block === null ? `${before}${after}` : `${before}${block}${after}`;
  return next === text ? null : next;
}

/**
 * The adapter-agnostic sync engine (master §9.1 flow + D10 conflict rules).
 *
 * @param props.root - Absolute project root.
 * @param props.reporter - Sink; one line per created/updated/deleted/conflict + final summary.
 * @returns EXIT.FINDINGS when any conflict was reported, else EXIT.OK.
 */
export function runSync(props: { root: string; reporter: Reporter }): number {
  const { ctx, warnings } = loadProjectContext({ root: props.root });
  for (const w of warnings) props.reporter.warn(w, "sync");
  const prev = loadSyncManifest({ root: props.root });
  const prevByPath = new Map(prev.entries.map((e) => [e.path, e]));

  // Desired state.
  const contextRulesYaml = buildContextRules({
    manifest: ctx.manifest,
    standards: ctx.standardsFiles.map((path) => {
      const text = readFileSync(join(props.root, AGENT_DIR, path), "utf8");
      const appliesTo = parseFrontmatter({ text }).data["applies_to"];
      return { path, appliesTo: Array.isArray(appliesTo) ? (appliesTo as string[]) : [] };
    }),
    namingScopes: ctx.contextRules?.some((r) => r.id === "naming")
      ? (ctx.contextRules.find((r) => r.id === "naming")?.when ?? null)
      : null,
  }).yaml;

  interface DesiredFile {
    path: string;
    content: string;
    platform: PlatformId | "core";
  }
  const files: DesiredFile[] = [{ path: P.contextRules, content: contextRulesYaml, platform: "core" }];
  const symlinks: Array<{ linkPath: string; targetPath: string; platform: PlatformId }> = [];
  const gitignoreLines: string[] = [".agent/dependencies/*"];
  const gitignorePlatform = new Map<string, PlatformId | "core">([[".agent/dependencies/*", "core"]]);

  for (const id of ctx.manifest.platforms.active) {
    const adapter = ADAPTERS[id];
    if (adapter === undefined) throw new HarnessError("unknown-platform", `no adapter for platform "${id}"`);
    const plan = adapter.plan({ ctx });
    for (const f of plan.files) files.push({ ...f, platform: id });
    for (const s of plan.symlinks) symlinks.push({ ...s, platform: id });
    for (const line of plan.gitignoreLines) {
      gitignoreLines.push(line);
      gitignorePlatform.set(line, id);
    }
  }
  files.sort((a, b) => (a.path < b.path ? -1 : 1));

  const nextEntries: SyncEntry[] = [];
  let created = 0;
  let updated = 0;
  let unchanged = 0;
  let deleted = 0;
  let conflicts = 0;

  const conflict = (path: string, msg: string, hint?: string): void => {
    conflicts++;
    props.reporter.warn(`${path}: ${msg}`, "sync", hint);
  };

  // FILES
  for (const f of files) {
    const abs = join(props.root, f.path);
    const diskText = existsSync(abs) && lstatSync(abs).isFile() ? readFileSync(abs, "utf8") : null;
    const prevEntry = prevByPath.get(f.path);

    if (MERGE_PATHS.has(f.path)) {
      const result = mergeManagedJson({ existingText: diskText, fragment: CLAUDE_SETTINGS_FRAGMENT });
      if (result.conflict !== undefined) {
        conflict(f.path, result.conflict);
        if (prevEntry !== undefined) nextEntries.push(prevEntry);
        continue;
      }
      const finalText = result.merged ?? (diskText as string);
      if (result.merged !== null) {
        writeFileAtomic({ path: abs, content: result.merged });
        if (diskText === null) {
          created++;
          props.reporter.info(`created ${f.path}`, "sync");
        } else {
          updated++;
          props.reporter.info(`updated ${f.path}`, "sync");
        }
      } else {
        unchanged++;
      }
      nextEntries.push({ path: f.path, kind: "generated", target_or_hash: sha256({ text: finalText }), platform: f.platform });
      continue;
    }

    if (diskText === null) {
      writeFileAtomic({ path: abs, content: f.content });
      created++;
      props.reporter.info(`created ${f.path}`, "sync");
    } else if (prevEntry !== undefined && sha256({ text: diskText }) === prevEntry.target_or_hash) {
      if (diskText === f.content) {
        unchanged++;
      } else {
        writeFileAtomic({ path: abs, content: f.content });
        updated++;
        props.reporter.info(`updated ${f.path}`, "sync");
      }
    } else if (prevEntry !== undefined) {
      conflict(f.path, "user-modified managed file — left in place", `move your edits into .agent/ and delete ${f.path}, then re-run harness sync`);
      nextEntries.push(prevEntry); // keep the stale entry (design decision)
      continue;
    } else {
      conflict(f.path, "exists but is not managed by harness — left untouched");
      continue;
    }
    nextEntries.push({ path: f.path, kind: "generated", target_or_hash: sha256({ text: f.content }), platform: f.platform });
  }

  // SYMLINKS
  for (const s of symlinks) {
    const result = ensureSymlink({
      linkPath: join(props.root, s.linkPath),
      targetPath: join(props.root, s.targetPath),
    });
    if (result === "created") {
      created++;
      props.reporter.info(`created ${s.linkPath} → ${s.targetPath}`, "sync");
    } else if (result === "replaced") {
      updated++;
      props.reporter.info(`repaired ${s.linkPath} → ${s.targetPath}`, "sync");
    } else if (result === "conflict") {
      conflict(s.linkPath, "exists but is not a harness symlink — left untouched");
      continue;
    } else {
      unchanged++;
    }
    nextEntries.push({ path: s.linkPath, kind: "symlink", target_or_hash: s.targetPath, platform: s.platform });
  }

  // DELETIONS — formerly-managed paths absent from the desired plan.
  const desiredPaths = new Set([...files.map((f) => f.path), ...symlinks.map((s) => s.linkPath)]);
  const emptyDirCandidates = new Set<string>();
  for (const entry of prev.entries) {
    if (entry.kind === "gitignore-line") continue; // handled by the block rewrite
    if (desiredPaths.has(entry.path)) continue;
    const abs = join(props.root, entry.path);
    let st;
    try {
      st = lstatSync(abs);
    } catch {
      deleted++; // already gone
      continue;
    }
    if (entry.kind === "symlink") {
      if (st.isSymbolicLink()) {
        unlinkSync(abs);
        deleted++;
        props.reporter.info(`deleted ${entry.path}`, "sync");
      } else {
        conflict(entry.path, "was managed, now removed from plan, but is no longer a symlink — delete manually");
        nextEntries.push(entry);
      }
    } else {
      const diskText = st.isFile() ? readFileSync(abs, "utf8") : null;
      if (diskText !== null && sha256({ text: diskText }) === entry.target_or_hash) {
        rmSync(abs);
        deleted++;
        props.reporter.info(`deleted ${entry.path}`, "sync");
      } else {
        conflict(entry.path, "was managed, now removed from plan, but user-modified — delete manually");
        nextEntries.push(entry);
      }
    }
    emptyDirCandidates.add(dirname(abs));
  }
  // Prune now-empty bridge dirs, deepest first.
  for (const dir of [...emptyDirCandidates].sort((a, b) => b.length - a.length)) {
    let current = dir;
    while (current.startsWith(props.root) && current !== props.root) {
      try {
        if (readdirSync(current).length > 0) break;
        rmdirSync(current);
      } catch {
        break;
      }
      current = dirname(current);
    }
  }

  // GITIGNORE
  const gitignoreAbs = join(props.root, ".gitignore");
  const sortedLines = [...new Set(gitignoreLines)].sort();
  const gitignoreText = existsSync(gitignoreAbs) ? readFileSync(gitignoreAbs, "utf8") : null;
  const nextGitignore = updateGitignoreBlock({ existingText: gitignoreText, lines: sortedLines });
  if (nextGitignore !== null) {
    writeFileAtomic({ path: gitignoreAbs, content: nextGitignore });
    props.reporter.info("updated .gitignore managed block", "sync");
  }
  for (const line of sortedLines) {
    nextEntries.push({
      path: `.gitignore#${line}`,
      kind: "gitignore-line",
      target_or_hash: line,
      platform: gitignorePlatform.get(line) ?? "core",
    });
  }

  saveSyncManifest({
    root: props.root,
    syncManifest: { version: 1, generated_at_sha: headSha({ root: props.root }), entries: nextEntries },
  });
  props.reporter.info(
    `sync: ${created} created, ${updated} updated, ${unchanged} unchanged, ${deleted} deleted, ${conflicts} conflicts`,
    "sync",
  );
  return conflicts > 0 ? EXIT.FINDINGS : EXIT.OK;
}
