import { describe, expect, test } from "bun:test";
import { existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, rmSync, symlinkSync, writeFileSync, appendFileSync } from "node:fs";
import { join } from "node:path";
import { gitInit, mkTmpProject, rmProject, runCli } from "../../test/helpers.ts";
import { sha256, walk } from "../lib/fsx.ts";
import { loadManifest, saveManifest } from "../lib/manifest.ts";
import { loadSyncManifest } from "../lib/syncManifest.ts";
import { buildContextRules, loadProjectContext, mergeManagedJson, updateGitignoreBlock } from "./sync.ts";

const CONTEXT_RULES_GOLDEN = `# GENERATED by harness sync — do not edit. Source: standards folders + naming rule scopes.
version: 1
rules:
  - id: std-backend
    when: ["convex/**", "src/server/**"]
    inject:
      - docs/standards/backend/api.md
  - id: naming
    when: ["src/components/**", "src/hooks/**", "src/lib/**"]
    inject:
      - docs/standards/naming-conventions.md
`;

describe("buildContextRules", () => {
  test("golden yaml from the initialized fixture (unsorted inputs → sorted output)", () => {
    const dir = mkTmpProject({ fixture: "initialized" });
    const { ctx, warnings } = loadProjectContext({ root: dir });
    expect(warnings).toEqual([]);
    expect(ctx.contextRules?.map((r) => r.id)).toEqual(["std-backend", "naming"]);
    const built = buildContextRules({
      manifest: ctx.manifest,
      standards: [{ path: "docs/standards/backend/api.md", appliesTo: ["src/server/**", "convex/**"] }],
      namingScopes: ["src/lib/**", "src/hooks/**", "src/components/**"],
    });
    expect(built.yaml).toBe(CONTEXT_RULES_GOLDEN);
    rmProject({ dir });
  });

  test("domain without applies_to → omitted with warning; empty rules → 'rules: []'", () => {
    const built = buildContextRules({
      manifest: { standards_domains: ["backend"] } as never,
      standards: [{ path: "docs/standards/backend/api.md", appliesTo: [] }],
      namingScopes: null,
    });
    expect(built.rules).toEqual([]);
    expect(built.warnings[0]).toContain("backend");
    expect(built.yaml).toContain("rules: []");
  });
});

describe("mergeManagedJson", () => {
  const FRAGMENT = {
    hooks: { SessionStart: [{ hooks: [{ type: "command", command: "harness doctor" }] }] },
  };

  test("null existing → full fragment text", () => {
    const r = mergeManagedJson({ existingText: null, fragment: FRAGMENT });
    expect(r.merged).toBe(`${JSON.stringify(FRAGMENT, null, 2)}\n`);
  });

  test("user keys and hook entries preserved; harness entry appended last", () => {
    const user = JSON.stringify({
      permissions: { allow: ["Bash(ls:*)"] },
      hooks: { SessionStart: [{ hooks: [{ type: "command", command: "echo hi" }] }] },
    });
    const r = mergeManagedJson({ existingText: user, fragment: FRAGMENT });
    const merged = JSON.parse(r.merged as string);
    expect(merged.permissions).toEqual({ allow: ["Bash(ls:*)"] });
    expect(merged.hooks.SessionStart).toHaveLength(2);
    expect(merged.hooks.SessionStart[0].hooks[0].command).toBe("echo hi");
    expect(merged.hooks.SessionStart[1].hooks[0].command).toBe("harness doctor");
    // Re-merge is a no-op.
    expect(mergeManagedJson({ existingText: r.merged as string, fragment: FRAGMENT }).merged).toBe(null);
  });

  test("invalid JSON → conflict, no merge", () => {
    const r = mergeManagedJson({ existingText: "not json{", fragment: FRAGMENT });
    expect(r.merged).toBe(null);
    expect(r.conflict).toContain("not valid JSON");
  });

  test("user entry already running harness doctor is not duplicated", () => {
    const user = `${JSON.stringify({ hooks: { SessionStart: [{ hooks: [{ type: "command", command: "harness doctor" }] }] } }, null, 2)}\n`;
    expect(mergeManagedJson({ existingText: user, fragment: FRAGMENT }).merged).toBe(null);
  });
});

describe("updateGitignoreBlock", () => {
  test("creates the block in a fresh file; preserves user lines on rewrite; removes cleanly", () => {
    const created = updateGitignoreBlock({ existingText: null, lines: [".omp/"] }) as string;
    expect(created).toContain("# >>> harness");
    expect(created).toContain(".omp/");

    const withUser = `node_modules/\n\n${created}`;
    const rewritten = updateGitignoreBlock({ existingText: withUser, lines: [".claude/", ".omp/"] }) as string;
    expect(rewritten.startsWith("node_modules/\n")).toBe(true);
    expect(rewritten).toContain(".claude/\n.omp/");

    const removed = updateGitignoreBlock({ existingText: rewritten, lines: [] }) as string;
    expect(removed).not.toContain("harness");
    expect(removed).toContain("node_modules/");

    expect(updateGitignoreBlock({ existingText: "user\n", lines: [] })).toBe(null);
  });
});

const OMP_FILES = [
  ".omp/agents/dev-spec.md",
  ".omp/agents/implement.md",
  ".omp/config.yml",
  ".omp/hooks/session-doctor.ts",
  ".omp/instructions/naming-0.instructions.md",
  ".omp/instructions/naming-1.instructions.md",
  ".omp/instructions/naming-2.instructions.md",
  ".omp/instructions/std-backend-0.instructions.md",
  ".omp/instructions/std-backend-1.instructions.md",
  ".omp/prompts/dev-spec.md",
  ".omp/prompts/implement.md",
];

function syncedFixture(): string {
  const dir = mkTmpProject({ fixture: "initialized" });
  gitInit({ dir });
  return dir;
}

function bridgeSnapshot(dir: string): Map<string, string> {
  const snap = new Map<string, string>();
  for (const rel of [...walk({ root: join(dir, ".omp") }).map((f) => `.omp/${f}`), ...walk({ root: join(dir, ".claude") }).map((f) => `.claude/${f}`), ".agent/context-rules.yaml", ".gitignore"]) {
    const abs = join(dir, rel);
    if (lstatSync(abs).isSymbolicLink()) snap.set(rel, `link:${readlinkSync(abs)}`);
    else snap.set(rel, sha256({ text: readFileSync(abs, "utf8") }));
  }
  return snap;
}

describe("runSync engine", () => {
  test("full first sync: files, symlinks, gitignore block, manifest", async () => {
    const dir = syncedFixture();
    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(0);

    for (const f of OMP_FILES) expect(existsSync(join(dir, f))).toBe(true);
    expect(readlinkSync(join(dir, ".omp/skills"))).toBe("../.agent/skills");
    expect(readlinkSync(join(dir, ".omp/AGENTS.md"))).toBe("../.agent/AGENTS.md");
    expect(readlinkSync(join(dir, ".claude/skills"))).toBe("../.agent/skills");
    expect(readFileSync(join(dir, ".agent/context-rules.yaml"), "utf8")).toBe(CONTEXT_RULES_GOLDEN);

    const gitignore = readFileSync(join(dir, ".gitignore"), "utf8");
    expect(gitignore).toContain(".agent/dependencies/*\n.claude/\n.omp/");

    const sm = loadSyncManifest({ root: dir });
    expect(sm.entries).toHaveLength(22); // 16 generated (incl. 4 command shims) + 3 symlinks + 3 gitignore-lines
    expect(sm.generated_at_sha).toMatch(/^[0-9a-f]{40}$/);
    const paths = sm.entries.map((e) => e.path);
    expect(paths).toEqual([...paths].sort());
    rmProject({ dir });
  });

  test("idempotency: second sync is a byte-identical no-op", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    const snap1 = bridgeSnapshot(dir);
    const r2 = await runCli({ argv: ["sync"], cwd: dir });
    expect(r2.code).toBe(0);
    expect(r2.stdout).toContain("0 created, 0 updated");
    expect(r2.stdout).toContain("0 deleted, 0 conflicts");
    expect(bridgeSnapshot(dir)).toEqual(snap1);
    rmProject({ dir });
  });

  test("D10a: source edit → managed file rewritten", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    const skillPath = join(dir, ".agent/skills/implement/SKILL.md");
    writeFileSync(skillPath, readFileSync(skillPath, "utf8").replace("Drive spec implementation", "Drive the spec implementation"));
    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(0);
    expect(r.stdout).toContain("updated .omp/agents/implement.md");
    expect(readFileSync(join(dir, ".omp/agents/implement.md"), "utf8")).toContain("Drive the spec implementation");
    rmProject({ dir });
  });

  test("D10b: user-modified managed file → conflict, left in place, entry kept", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    const oldHash = loadSyncManifest({ root: dir }).entries.find((e) => e.path === ".omp/config.yml")?.target_or_hash;
    appendFileSync(join(dir, ".omp/config.yml"), "# mine\n");
    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(1);
    expect(r.stdout).toContain(".omp/config.yml: user-modified managed file");
    expect(readFileSync(join(dir, ".omp/config.yml"), "utf8")).toEndWith("# mine\n");
    expect(loadSyncManifest({ root: dir }).entries.find((e) => e.path === ".omp/config.yml")?.target_or_hash).toBe(oldHash);
    rmProject({ dir });
  });

  test("D10c: unmanaged existing file → conflict, never touched, no entry", async () => {
    const dir = syncedFixture();
    mkdirSync(join(dir, ".claude"), { recursive: true });
    writeFileSync(join(dir, ".claude/CLAUDE.md"), "custom\n");
    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(1);
    expect(r.stdout).toContain(".claude/CLAUDE.md: exists but is not managed");
    expect(readFileSync(join(dir, ".claude/CLAUDE.md"), "utf8")).toBe("custom\n");
    expect(loadSyncManifest({ root: dir }).entries.some((e) => e.path === ".claude/CLAUDE.md")).toBe(false);
    expect(existsSync(join(dir, ".omp/config.yml"))).toBe(true); // everything else created
    rmProject({ dir });
  });

  test("D10d: deactivating a platform cleans its bridge entirely", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    const { manifest } = loadManifest({ root: dir });
    manifest.platforms.active = ["omp"];
    saveManifest({ root: dir, manifest });
    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(0);
    expect(existsSync(join(dir, ".claude"))).toBe(false);
    expect(readFileSync(join(dir, ".gitignore"), "utf8")).not.toContain(".claude/");
    expect(loadSyncManifest({ root: dir }).entries.some((e) => e.platform === "claude")).toBe(false);
    rmProject({ dir });
  });

  test("symlink repair and symlink conflict", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    rmSync(join(dir, ".omp/skills"));
    symlinkSync("../nowhere", join(dir, ".omp/skills"));
    let r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.stdout).toContain("repaired .omp/skills");
    expect(readlinkSync(join(dir, ".omp/skills"))).toBe("../.agent/skills");

    rmSync(join(dir, ".claude/skills"));
    mkdirSync(join(dir, ".claude/skills"));
    r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(1);
    expect(r.stdout).toContain(".claude/skills: exists but is not a harness symlink");
    expect(lstatSync(join(dir, ".claude/skills")).isDirectory()).toBe(true);
    rmProject({ dir });
  });

  test("settings.json merge preserves user pieces; re-sync byte-identical", async () => {
    const dir = syncedFixture();
    await runCli({ argv: ["sync"], cwd: dir });
    const settingsPath = join(dir, ".claude/settings.json");
    const withUser = JSON.parse(readFileSync(settingsPath, "utf8"));
    withUser.permissions = { allow: ["Bash(ls:*)"] };
    withUser.hooks.SessionStart.unshift({ hooks: [{ type: "command", command: "echo hi" }] });
    writeFileSync(settingsPath, `${JSON.stringify(withUser, null, 2)}\n`);

    const r = await runCli({ argv: ["sync"], cwd: dir });
    expect(r.code).toBe(0); // merge path — never a conflict
    const after = JSON.parse(readFileSync(settingsPath, "utf8"));
    expect(after.permissions).toEqual({ allow: ["Bash(ls:*)"] });
    expect(after.hooks.SessionStart[0].hooks[0].command).toBe("echo hi");
    expect(after.hooks.SessionStart.some((e: { hooks: Array<{ command: string }> }) => e.hooks[0]?.command === "harness doctor")).toBe(true);

    const hash1 = sha256({ text: readFileSync(settingsPath, "utf8") });
    await runCli({ argv: ["sync"], cwd: dir });
    expect(sha256({ text: readFileSync(settingsPath, "utf8") })).toBe(hash1);
    rmProject({ dir });
  });
});
